name: Terraform Apply KeyVault

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply â€“ KEY VAULT ONLY
        working-directory: infra
        run: terraform apply -auto-approve \
             -target=azurerm_key_vault.keyvault \
             -target=azurerm_role_assignment.keyvault_admin \
             -target=azurerm_role_assignment.backend_kv_secrets \
             -target=azurerm_key_vault_secret.db_username \
             -target=azurerm_key_vault_secret.db_password \
             -target=azurerm_key_vault_secret.db_database \
             -target=azurerm_private_endpoint.pe_keyvault \
             -target=azurerm_private_dns_zone.kv_dns \
             -target=azurerm_private_dns_zone_virtual_network_link.kv_dns_link \
             -target=azurerm_private_dns_a_record.kv_a_record
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id:       ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_resource_group_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
          TF_VAR_location:              ${{ secrets.TF_VAR_LOCATION }}
          TF_VAR_key_vault_name:        ${{ secrets.TF_VAR_KEY_VAULT_NAME }}
          TF_VAR_sql_admin_login:       ${{ secrets.TF_VAR_SQL_ADMIN_LOGIN }}
          TF_VAR_sql_admin_password:    ${{ secrets.TF_VAR_SQL_ADMIN_PASSWORD }}
          TF_VAR_database_name:         ${{ secrets.TF_VAR_DATABASE_NAME }}

